name: CI

on:
  pull_request:
  push:
    branches: [main]
    tags: ["*"]

jobs:
  swift:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Swift Package Describe
        run: swift package describe

      - name: Swift Build
        run: swift build -j 2

      - name: Swift Test
        run: swift test -j 2

      - name: Swift Release Build
        run: swift build -j 2 -c release

      - name: iOS Generic Build
        run: xcodebuild -scheme ConveltKit -destination 'generic/platform=iOS' build
